package com.news.app.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.fasterxml.jackson.annotation.JsonProperty

@Entity
data class Source(
    @PrimaryKey
    var id: Int? = null,
    //ID GENERATED BY NEWSAPI
    @JsonProperty("id")
    var sourceId: String? = null,
    var name: String,
    var description: String? =null,
    var url: String? = null,
    var category:String? = null,
    var language: String? = null,
    var country: String? = null)