package com.news.app.models

import com.fasterxml.jackson.annotation.JsonProperty
import javax.persistence.*

//@Entity
data class Source(
            //ID GENERATED BY NEWSAPI
             var id: String?="",
             var name: String="",
             var description: String?="",
             var url: String?="",
             var category:String?="",
             var language: String?="",
             var country: String?="")