package com.news.app.models

import com.fasterxml.jackson.annotation.JsonProperty
import javax.persistence.*

//@Entity
data class Source(
        //@Id
        //@GeneratedValue(strategy = GenerationType.IDENTITY)
            //var id: Int? = null,
            //ID GENERATED BY NEWSAPI
        @JsonProperty("id")
             var sourceId: String?="",
             var name: String="",
             var description: String?="",
             var url: String?="",
             var category:String?="",
             var language: String?="",
             var country: String?="")