name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with: 
          java-version: 
            1.8
    - name: Package
      working-directory: ./back
      run: |
        mvn clean install
        mvn package
        mv target/*jar target/app.jar
    - name: Upload target
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: back/target/app.jar
  dockerize:
    needs: [java-build]
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: docker
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        working-directory: ./
        run: |
          ls target
          mv target/*.jar back/target/app.jar
          docker build -t nahellachgar/appli-actus:latest ./back
          docker push nahellachgar/appli-actus:tagname    
