name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with: 
          java-version: 
            1.8
    - name: Package
      working-directory: ./back
      run: mvn package
  dockerize:
    needs: [java-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build
      working-directory: ./
      run: |
        ls
        docker build -t nahellachgar/appli-actus:latest .
        docker push nahellachgar/appli-actus:tagname    
